// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ginTest/internal/controller"
	"ginTest/internal/middleware"
	"ginTest/internal/repository"
	"ginTest/internal/routes"
	"ginTest/internal/service"
)

// Injectors from wire.go:

func InitializeApp() *routes.App {
	db := repository.NewDB()
	userRepo := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepo)
	userController := controller.NewUserController(userService)
	client := middleware.NewRedis()
	authService := service.NewAuthService(userRepo, client)
	authController := controller.NewAuthController(authService)
	userRoute := routes.NewUserRoute(userController, authController)
	app := routes.NewApp(userRoute)
	return app
}
