#先写配置文件
app:
  port: 8080
database:
  driver: mysql
  dsn: "root:12345@tcp(127.0.0.1:3306)/heimaDianping?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  addr: "127.0.0.1:6379"
  password: "12345"
  db: 1
